# Generated by Django 3.2.15 on 2023-02-22 05:00

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHealthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
            ],
            options={
                'db_table': 'OpenHealth_table',
            },
        ),
        migrations.CreateModel(
            name='otp_loggs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('date_time', models.DateTimeField()),
                ('expiry_on', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bot_otp_log',
            },
        ),
        migrations.CreateModel(
            name='otp_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('date_time', models.DateTimeField()),
                ('expiry_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'bot_otp_table',
            },
        ),
        migrations.CreateModel(
            name='QuestionDepressionTableV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentId', models.IntegerField(default=2)),
                ('Question', models.CharField(max_length=500)),
                ('Category', models.CharField(default='Depression', max_length=100)),
                ('Sub_category', models.CharField(choices=[('Depression', 'Depression')], max_length=30)),
            ],
            options={
                'db_table': 'Depression Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionDiabetesTableV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentId', models.IntegerField(default=3)),
                ('Question', models.CharField(max_length=500)),
                ('Category', models.CharField(default='Diabetes', max_length=100)),
                ('Sub_category', models.CharField(choices=[('Diabetes', 'Diabetes')], max_length=30)),
            ],
            options={
                'db_table': 'Diabetes Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionLifestyleScoresTableV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssessmentId', models.IntegerField(default=1)),
                ('Question', models.CharField(max_length=500)),
                ('Category', models.CharField(default='lifestyle scoring', max_length=100)),
                ('Sub_category', models.CharField(choices=[('Connectedness', 'Connectedness'), ('Movement', 'Movement'), ('Nutrition', 'Nutrition'), ('Recovery', 'Recovery'), ('SubstanceUse', 'SubstanceUse')], max_length=30)),
            ],
            options={
                'db_table': 'Lifestyle scoring Questions',
            },
        ),
        migrations.CreateModel(
            name='OpenhealthLifestyleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyId', models.CharField(default=None, max_length=255)),
                ('Age', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes')], default='Lifestyle', max_length=100)),
                ('Sub_category', models.CharField(choices=[('Connectedness', 'Connectedness'), ('Movement', 'Movement'), ('Nutrition', 'Nutrition'), ('Recovery', 'Recovery'), ('SubstanceUse', 'SubstanceUse')], max_length=100)),
                ('AssessmentId', models.IntegerField(default=1)),
                ('InteractionId', models.IntegerField()),
                ('Answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('less than 1', 'less than 1'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10+', '10+'), ('less than 30', 'less than 30'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('120', '120'), ('150', '150'), ('180', '180'), ('210', '210'), ('240', '240'), ('270', '270'), ('300+', '300+')], max_length=20)),
                ('Score', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpenhealthLifestyle', to='openhealthapi.questionlifestylescorestablev2')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOpenhealthLifestyle', to='openhealthapi.openhealthmodel')),
            ],
            options={
                'db_table': 'Openhealth_Lifestyle_Assessment_table',
            },
        ),
        migrations.CreateModel(
            name='OpenhealthInteractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyId', models.CharField(default=None, max_length=255)),
                ('InteractionId', models.IntegerField()),
                ('Category', models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Depression', 'Depression'), ('Diabetes', 'Diabetes')], max_length=100)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Openhealth_InteractionUser', to='openhealthapi.openhealthmodel')),
            ],
            options={
                'db_table': 'Openhealth_InteractionTable',
            },
        ),
        migrations.CreateModel(
            name='OpenhealthDiabetesAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyId', models.CharField(default=None, max_length=25)),
                ('Age', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('Diabetes', 'Diabetes')], max_length=100)),
                ('AssessmentId', models.IntegerField(default=3)),
                ('InteractionId', models.IntegerField()),
                ('Answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('less than 1', 'less than 1'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10+', '10+'), ('less than 30', 'less than 30'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('120', '120'), ('150', '150'), ('180', '180'), ('210', '210'), ('240', '240'), ('270', '270'), ('300+', '300+')], max_length=20)),
                ('Score', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpenhealthDiabetes', to='openhealthapi.questiondiabetestablev2')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOpenhealthDiabetes', to='openhealthapi.openhealthmodel')),
            ],
            options={
                'db_table': 'Openhealth_Diabetes_Assessment_table',
            },
        ),
        migrations.CreateModel(
            name='OpenhealthDepressionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyId', models.CharField(default=None, max_length=255)),
                ('Age', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('Depression', 'Depression')], max_length=100)),
                ('AssessmentId', models.IntegerField(default=2)),
                ('InteractionId', models.IntegerField()),
                ('Answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('less than 1', 'less than 1'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10+', '10+'), ('less than 30', 'less than 30'), ('30', '30'), ('45', '45'), ('60', '60'), ('90', '90'), ('120', '120'), ('150', '150'), ('180', '180'), ('210', '210'), ('240', '240'), ('270', '270'), ('300+', '300+')], max_length=20)),
                ('Score', models.IntegerField()),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.today)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpenhealthDepression', to='openhealthapi.questiondepressiontablev2')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserOpenhealthDepression', to='openhealthapi.openhealthmodel')),
            ],
            options={
                'db_table': 'Openhealth_Depression_Assessment_table',
            },
        ),
        migrations.CreateModel(
            name='demographicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(choices=[('white', 'WHITE'), ('Black or African American', 'BLACK OR AFRICAN AMERICAN'), ('Asian', 'ASIAN'), ('Native Hawaiian or Other Pacific Islander', 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER'), ('American Indian or Alaska Native', 'AMERICAN INDIAN OR ALASKA NATIVE'), ('Hispanic or Latino', 'HISPANIC OR LATINO')], default='', max_length=50)),
                ('InteractionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_democratic_table', to='openhealthapi.otp_model')),
            ],
            options={
                'db_table': 'bot_demographic_table',
            },
        ),
    ]
